# -*- coding: utf-8 -*-
"""FuncionesCargaDatos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xrm8yY_3bWARqNkjBAzcBRySlddu4ngH

#**Funciones de descarga de las señales desde PhysioNet y de carga en el entorno de trabajo**
"""



"""Importación de las librerías necesarias para las funciones"""

import os
import wfdb
from google.colab import drive

"""## Función que descarga los archivos desde PhysioNet

"""

def descarga_archivos_physionet (ruta_drive, ruta_dataset):
  """
  Función que descarga de forma permanente el dataset de PhysioNet que indiquemos en el directorio de Google Drive especificado.

  Parámetros
  ------------
    - ruta_drive (str): Ruta en que se encuentra el dataset. Esta es relativa, es decir, no hace falta indicar el dominio.
        Ejemplo: 'challenge-2017/training'

    - ruta_dataset (str):  Ruta al directorio de Drive en el que se almacenan los archivos. Esta es completa, es necesario indicar '/content/drive/MyDrive' antes.
        Ejemplo: '/content/drive/MyDrive/dataset_ECG'


  Return
  ------------
    - None: Solo muestra por pantalla la confirmación de que los archivos se han descargado correctamente, cuando esto ha sido así. En el caso contrario, muestra un mensaje de
    error, a través de una excepción, indicando que no se ha podido completar la descarga.


  Raises
  ---------
    - ValueError: Error que indica que no se ha podido completar la descarga, debido a que la ruta proporcionada por el usuario no es correcta.

  """

  from google.colab import drive                                # Importamos la biblioteca de Google Drive dentro de la función para poder conectarse a este
  drive.mount('/content/drive')                                 # Conexión del entorno de trabajo con Google Drive para almacenar los archivos

  os.makedirs(ruta_drive, exist_ok=True)                        # Creamos el directorio en el que se van a almacenar los archivos en el caso de que este no exista


  try:                                                          # Intenta descargar el set de datos desde la ruta que le hemos proporcionado
    wfdb.dl_database(ruta_dataset, dl_dir=ruta_drive)           # Realizamos la descarga de los archivos desde PhysioNet en la dirección indicada
    print (f"Los archivos se han descargado correctamente en la dirección {ruta_drive}")     # Confirmación por pantalla de que la descarga ha sido satisfactoria

  except Exception as e:                                   # Si la ruta proporcionada no es correcta, nos muestra por pantalla que no ha sido posible completar la descarga (error)
    raise ValueError (f"Error al descargar el set de datos '{ruta_dataset}' desde PhysioNet. Inténtalo de nuevo.")



"""## Funciones para cargar los archivos desde Drive en el entorno de trabajo (Google Colab) para poder trabajar con ellos"""

def carga_archivos_entorno (ruta_directorio, archivos=None):

  """
  Esta función carga desde el directorio de Google Drive pasado como argumento, los archivos válidos que se listan en el parámetro 'archivos' en el caso de
  que este exista, y, en caso contrario, todos aquellos que se encuentren en dicho directorio. Todos ellos deben contar con extensión '.hea'.
  A partir de cada uno de estos, la función crea un objeto de tipo wfdb.Record con la información almacenada en formato '.hea' y '.mat' para cada uno de ellos, utilizando
  para ello la biblioteca WFDB.
  Estos archivos wfdb.Record son almacenados en un diccionario, que va a ser el Return de la función, para poder ser visualizados o trabajar con ellos una vez recuperados.

  Parámetros
  -------------
    - ruta_directorio (str): Ruta del directorio de Google Drive en el que se encuentran los archivos que queremos cargar en nuestro entorno de trabajo.
        Ejemplo: '/content/drive/MyDrive/dataset_ECG_2017'

    - archivos= None (list): Lista con los nombres de los archivos que queremos cargar en formato '.hea', en el caso de que solo queramos cargar una parte de los archivos del directorio,
    no la totalidad de estos.
        Ejemplo: ['A00291.hea', 'A00483.hea']


  Return
  -------------
    - ecg_cargados (dict): Diccionario en el que se encuentran los objetos tipo wfdb.Record creados a partir de cada registro, indexados por el nombre de estos, sin extensión.
      Ejemplo: {'A00291': wfdb.Record}


  Raises
  ----------
    - ValueError: Nos devuelve un error si la extensión del archivo que queremos cargar no es '.hea', por lo que no es válida para nuestro trabajo.

  """
  from google.colab import drive
  drive.mount('/content/drive')                                              # Nos conectamos al Drive para poder recuperar los archivos desde su ubicación en Drive

  ecg_cargados = {}                                                          # Diccionario vacío, en el que vamos a almacenar los objetos tipo wfdb.Record generados
  if archivos and isinstance(archivos, list):                                # Comprueba si se ha pasado el argumento "archivos" para entrar en el bucle
    for i in archivos:                                                       # Recorremos la lista que contiene los nombres de los archivos '.hea' que queremos cargar
      if i.endswith('.hea'):                                                 # Comprobamos que los archivos presentan la extensión adecuada ('.hea')
        id = i.replace('.hea', '')                                           # Eliminamos la extensión del nombre del archivo, para establecer la ruta de carga
        nombre, record = proceso_interno_carga (ruta_directorio, id)         # Llamamos a la función que va a realizar la carga de los archivos en sí misma
        if record is not None:                                               # Comprueba que el registro indicado se ha cargado correctamente en el entorno de trabajo
          ecg_cargados[nombre] = record                                      # Almacena el objeto que acaba de crear en el diccionario 'ecg_cargados'

      else:                                                                  # Si el archivo no tiene la extensión adecuada ('.hea'), se imprime el siguiente error por pantalla
        raise ValueError (f"El archivo {i} no es un archivo '.hea', por lo que no es válido. Inténtalo de nuevo.")

  else:                                                                      # Si no existe el argumento "archivos" se realiza la carga de todos los archivos presentes en el directorio
    for e in os.listdir(ruta_directorio):                                    # Se van a recorrer todos los registros del directorio para proceder a su carga de forma individual
      if e.endswith('.hea'):                                                 # Se comprueba que el archivo sea del tipo '.hea'
        id = e.replace('.hea', '')                                           # Se elimina la extensión del nombre del archivo, para establecer la ruta de carga
        nombre, record = proceso_interno_carga (ruta_directorio, id)         # Llamamos a la función que va a realizar la carga del archivo ECG en sí misma
        if record is not None:                                               # Comprueba si la carga ha sido correcta
          ecg_cargados[nombre] = record                                      # Almacena los datos que acaba de cargar en el diccionario, indexados por el nombre del registro

  return ecg_cargados                                                        # Devuelve el diccionario con los archivos wfdb.Record que han sido creados

def proceso_interno_carga (ruta_directorio, nombre_archivo):

  """
  Esta función lleva a cabo la carga en sí misma del archivo pasado como argumento en el entorno de trabajo desde el que se invoca. Para ello crea un objeto de tipo wfdb.Record
  combinando los datos almacenados tanto en formato '.hea' como '.mat' para ese registro y es el que devuelvecuando se llama a esta función.

  Parámetros
  --------------
    - ruta_directorio (str): Directorio de Google Drive en el que se encuentran los archivos con los que queremos trabajar en el entorno de trabajo
        Ejemplo: '/content/drive/MyDrive/dataset_ECG/train'

    - nombre_archivo(str): Nombre con el que se almacena el ECG que va a ser cargado para poder trabajar con él, sin extensión
        Ejemplo: "A00037"

  Return
  --------------
    - nombre_archivo (str): Nombre del archivo que se ha cargado, sin extensión

    - record --> wfdb.Record o None: Si se ha podido cargar el archivo, la función devuelve el objeto de tipo Record, y en caso contrario no devuelve nada


    Raises
  ----------
    - ValueError: Error que nos proporciona la función cuando la carga de un archivo no ha sido satisfactoria.

  """

  ruta_completa_archivo = os.path.join(ruta_directorio, nombre_archivo)           # Ruta completa en la que se encuentra el archivo a cargar

  try:                                                                            # Intenta hacer la carga de los datos desde Google Drive
    record = wfdb.rdrecord(ruta_completa_archivo)                                 # Creación del objeto wfdb.Record a partir de los archivos '.hea' y '.mat' de dicho registro
    print(f"Se ha cargado el archivo {nombre_archivo} correctamente.")          # Confirmación por pantalla de que la carga ha sido satisfactoria
    return nombre_archivo, record                                                 # Devolución del identificador del archivo cargado y el objeto wfdb.Record que ha creado

  except Exception as e:                                                          # Si la carga no ha sido satisfactoria, muestra un mensaje de error por pantalla
    raise ValueError(f"Error al cargar el archivo {nombre_archivo}: {e}. Inténtalo de nuevo.")
    return nombre_archivo, None                                                   # Devolución del nombre del archivo que no ha sido posible cargar, y de un objeto vacío