# -*- coding: utf-8 -*-
"""FuncionesClasificacionSenales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nk_HUj6s_sXKB1zh9w_V6nNdIfrqflks

#**Funciones que llevan a cabo la preparación de los datos procesados para poder utilizarlos en el entrenamiento de la red GAN**
"""



# Importamos las bibliotecas necesarias para las distintas funciones

import pandas as pd
import os
import pickle
import sys



# Nos montamos a Google Drive para poder cargar los archivos con las funciones necesarias

from google.colab import drive
drive.mount('/content/drive')

# Añadimos la ruta en la que se enceuntran estos archivos para poder acceder a ellos

sys.path.append('/content/drive/MyDrive/programacion_ECG')

from funcionescargadatos import *



"""# Función que descarga el archivo con los valores de clasificación de las señales"""

def descargar_archivo_clasificacion (ruta_csv, ruta_drive, nombre_archivo):

  """
  Esta función realiza la descarga de un archivo con extensión '.csv' desde la ruta 'ruta_csv' pasada como argumento en la ruta 'ruta_drive' bajo el nombre de 'nombre_archivo.
  Principalmente, sirve para descargar los archivos que encontramos en la base de datos de PhysioNet y que relacionan el nombre de cada uno de los registros con los que vamos a
  trabajar con su condición clínica, es decir, recoge la clasificación de estos.
  Es importante indicar el tipo de separador que va a utilizar nuestro archivo (coma en este caso) para evitar posibles problemas de lectura.
  Además, convierte este archivo con extensión '.csv' en un DataFram de Pandas, y lo devuelve como resultado, de forma que podamos trabajar con él en Python de una forma mucho
  más sencilla, y con mayor eficacia.

  Parámetros
  -------------
    - ruta_csv (str): Ruta de PhysioNet en la que se encuentra el archivo con extensión '.csv' que recoge la clasificación de los registros de ECG con los que vamos a trabajar.
      Ejemplo: "https://physionet.org/files/challenge-2017/1.0.0/REFERENCE-v0.csv"

    - ruta_drive (str): Ruta de Google Drive en la que se va a almacenar el archivo descargado desde la ruta 'ruta_csv', que correponde a la ruta PhysioNet.
      Ejemplo: "/content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion"

    - nombre_archivo (str): Identificador con el que se va a almacenar el archivo descargado, en la ruta 'ruta_drive' pasada como argumento.
      Ejemplo: "REFERENCE-v0.csv"

  Return
  -------------
    - archivo_df (DataFrame): Objeto DataFrame que se ha creado a partir del archivo con extensión '.csv' descargado desde la ruta 'ruta_csv' de PhysioNet.

  Raises
  -------------
    - IsADirectoryError: La función muestra un mensaje de error si en lugar de especificar una ruta a un archivo (el que vamos a almacenar), esta corresponde a un directorio
    - ValueError: Se muestra un mensaje de error por pantalla si no se puede completar la descarga del archivo desde la ruta especificada.

    """

  from google.colab import drive                                   # Monta o se conecta a Google Drive para poder almacenar el archivo con extensión '.csv'
  drive.mount('/content/drive')

  os.makedirs(ruta_drive, exist_ok=True)                           # Comprueba si existe un directorio con el nombre 'ruta_drive', y si no es así, lo crea en Google Drive


  try:                                                             # Intenta realizar la descarga del archivo de clasificación desde Google Drive
    archivo_df = pd.read_csv(ruta_csv, sep = ',', header = None)   # Realiza la lectura del archivo con extensión '.csv'. Es como que accede a él de esta manera
    ruta_guardado = os.path.join(str(ruta_drive), str(nombre_archivo))   # Crea la ruta de guardado del archivo, incluyendo el nombre con el que se va a almacenar este

    if os.path.isdir(ruta_guardado):                               # Comprueba si la ruta es un directorio, y en caso afirmativo, muestra un error por pantalla
      raise IsADirectoryError(f"La ruta {ruta_guardado} es un directorio y se necesita un nombre de archivo para el almacenamiento del mismo. Inténtalo de nuevo.")

    archivo_csv = archivo_df.to_csv(ruta_guardado, index=False)                 # Si no es un directorio, realiza el guardado del archivo en la dirección 'ruta_guardado'

    if os.path.exists(ruta_guardado):                              # Comprueba si el archivo se ha guardado correctamente en la ruta especificada y muestra la confirmación
      print (f"El archivo .csv se ha guardado correctamente en la ruta pasada como argumento: {ruta_guardado}")

    return archivo_df

  except Exception as e:                                           # Si no es posible realizar la descarga del archivo, muestra un mensaje de error por pantalla
    raise ValueError (f" Ha ocurrido un error durante la descarga del archivo desde la ruta: {ruta_csv}. Inténtalo de nuevo")



"""# Función que carga el archivo con los valores de ejecución en el entorno de trabajo"""

def carga_archivo_clasificacion (ruta_drive, valor_clasificacion = 0,  nombre_generico = "df_clasificacion", verbose = False):

  """
  Esta función carga un archivo con extensión '.csv' desde la ruta de Google Drive en que se encuentra y devuelve este en forma de DataFrame de pandas.
  Este archivo contiene la clase a la que pertenece cada registro, por lo que va a permitir llevar más tarde el proceso de división de las distintas señales en función de
  la clase a la que pertenece cada una de ellas.
  Es importante tener en cuenta que la función puede cargar archivos tanto con un valor de clasificación específico, como archivos más generales que incluyan varios valores
  de clasificación.

  Parámetros
  -------------
    - ruta_drive (str): Ruta de Google Drive en la que se encuentra el archivo con extensión '.csv' que contiene la clasificación de los registros de ECG.
    - valor_clasificacion (int, optional): Valor que indica el archivo de clasificación que se quiere cargar en el entorno de trabajo. En caso de ser 0, se carga uno genérico.
    - nombre_generico (str, optional): Se indica el nombre genérico (sin tipo de clase) que va a presentar el archivo que se quiere cargar en el entorno de trabajo.
    - verbose (bool, optional): Parámetro booleano que indica si se va a mostrar información adicional por pantalla del DataFrame en caso de que sea True. Es False por defecto.

  Return
  -------------
    - df_clasificacion (DataFrame): Objeto DataFrame que se ha creado a partir del archivo con extensión '.csv' cargado desde la ruta especificada en Drive.

  Raises
  -------------
    - ValueError: Si el archivo no se encuentra en la ruta especificada, se muestra un mensaje de error por pantalla.



  """

  if valor_clasificacion == 0:                                           # Entra en el bucle en el caso de que no se haya especificado un valor de clasificación, o este sea 0
    nombre_archivo = str (nombre_generico ) + ".csv"                     # Crea una cadena de texto con el nombre que tiene el archivo en la ruta en que se encuentra
    ruta_archivo = os.path.join(str(ruta_drive), str(nombre_archivo))    # Crea una cadena de texto con la ruta completa al archivo que se quiere cargar

  else:                                                                  # En el caso de que si se haya pasado un 'valor_clasificacion' como argumento entra en el bucle
    nombre_archivo = str (nombre_generico) + "_" + str(valor_clasificacion) + ".csv"    # Crea una cadena de texto con la ruta relativa, en la que se incluye la clase
    ruta_archivo = os.path.join(str(ruta_drive), str(nombre_archivo))    # Instaura una ruta al archivo con el valor de clasificación pasado como argumento en Google Drive

  if not os.path.exists(ruta_archivo):                                   # En el caso de que el archivo no se encuentre en la ruta especificada muestra un mensaje de error por pantalla
    raise ValueError (f"El archivo {nombre_archivo} no se encuentra en la ruta especificada. Inténtelo de nuevo. ")


  df_clasificacion = pd.read_csv (ruta_archivo)                          # Realiza la lectura del archivo en forma de DataFrame desde la ruta especificada

  if verbose:                                                            # Si el valor 'verbose' es True muestra información adicional por pantalla
    print(f"Archivo cargado: {nombre_archivo}")                          # Imprime el nombre del archivo que se ha cargado
    print(f"Ruta en Drive del archivo: {ruta_archivo}")                  # Imprime la ruta en la que se encuentra el archivo
    print(f"Dimensiones del DataFrame: {df_clasificacion.shape}")        # Imprime las dimensiones del Dataframe (alto x ancho)
    print(df_clasificacion.head())                                       # Imprime las primeras filas del DataFrame

  return df_clasificacion                                                # Devuelve el DataFrame que contiene la relación entre las señales y la clase a la que pertenecen



"""# Función que modifica el DataFrame con los datos en función del valor de clasificación"""

def obtener_parametros_df (dataframe, nombres_columnas, verbose):

  """
  Esta función modifica los nombres de las columnas del DataFrame pasado como argumento. El nombre de cada una de estas columnas va a corresponder a cada uno de los elementos
  de la lista 'nombres_columnas' pasada como argumento. Por lo tanto, para que sea posible realizar la asignación de los nombres a las columnas correspondientes es necesario que
  la lista presente tantos elementos como columnas integren el DataFrame.
  Además, la función muestra información adicional por pantalla, cuando el parámetro booleano 'verbose' reciba el argumento True. En caso de que esto ocurra, la función
  imprimirá tanto el número de registros que contiene para cada valor de la segunda columna, como el total de registros que contiene el DataFrame.


  Parámetros
  -------------
    - dataframe (pd.DataFrame): DataFrame original con los valores de clasificación sobre el que vamos a trabajar.

    - nombres_columnas (list): Lista que contiene tantos elementos de tipo string como columnas presenta el DataFrame y contiene los futuros nombres de estas columnas.
      Ejemplo: ["id_señal", "etiqueta_clasificacion"]

    - verbose (bool, optional): Parámetro booleano que en caso de ser True muestra información adicional acerca del DataFrame por pantalla.

  Return
  -------------
    - dataframe_modificado (pd.DataFrame): DataFrame al que se le han modificado los nombres de las columnas, por los que aparecen en la lista 'nombres_columnas'


  Raises
  -------------
    - ValueError: Si la longitud de la lista 'nombres_columnas' no es igual al número de columnas del DataFrame, se muestra un mensaje de error por pantalla, porque no puede hacer
    la asignación de los nombres de las columnas correctamente.


  """

  if len(nombres_columnas) == dataframe.shape[1]:                          # Comprueba que la longitud de 'nombres_columnas' sea igual al número de columnas del DataFrame
    dataframe_modificado = dataframe.copy()                                # Realiza una copia del DataFrame original pasado como argumento
    dataframe_modificado.columns = nombres_columnas                        # Modifica los nombres de las columnas del DataFrame

  else:                                                                    # Si las longitudes no son iguales muestra un mensaje de error por pantalla
    raise ValueError(f"La longitud del parámetro 'nombres_columnas': {len(nombres_columnas)} debe ser igual al número de columnas del Dataframe: {dataframe.shape[1]}")


  if verbose:                                                              # Si el valor 'verbose' es True muestra información adicional por pantalla
    print (dataframe_modificado[nombres_columnas[1]].value_counts())       # Imprime el número de registros con cada valor único de la segunda columna del DataFrame
    print (len(dataframe_modificado))                                      # Imprime el número total de registros del DataFrame cuyos índices han sido modificados

  return dataframe_modificado                                              # Devuelve el DataFrame con los nombres de las columnas actualizados



"""# Función que obtiene un archivo con los datos de una determinada clase"""

def obtener_archivo_valor (dataframe, nombres_columnas, valor_clasificacion, ruta_drive, verbose=False):

  """
  Esta función filtra el DataFrame pasado como argumento según el valor de clasificación pasado también como argumento, que equivale a una de las condiciones clínicas
  presentes en los registros del DataFrame y almacena este archivo resultante con extensión '.csv' en la ruta de Google Drive que se pasa como argumento.
  Además, si el parámetro booleano 'verbose' es True, muestra información adicional por pantalla acerca de los registros que contiene el DataFrame pasado como argumento.


  Parámetros
  -------------
    - dataframe (pd.DataFrame): DarataFrame original sobre el que se va a realizar el filtrado en función del valor de clasificación 'valor_clasificacion' pasado como argumento.

    - nombres_columnas (list): Lista con los nombres que se van a asignar a cada una de las columnas de las que se compone el DataFrame original.
      Ejemplo: ["id_señal", "etiqueta_clasificacion"]

    - valor_clasificacion (str): Valor de filtrado del DataFrame , se van a almacenar en un archivo '.csv' todos los registros que presenten dicho valor.
      Ejemplo: "N", "A", "O", "~"

    - ruta_drive (str): Ruta absoluta de Google Drive en la que se va a almacenar el archivo con extensión '.csv' con los registros que han sido filtrados.
      Ejemplo: "/content/drive/MyDrive/dataset_ECG/challenge2017/clasificacion"

    - verbose = False (bool, optional): Parámetro booleano que indica si se va a mostrar información adicional por pantalla del DataFrame en caso de que sea True. Es False por defecto.


  Return
  -------------
    - None: Esta función no devuelve nada, sino que realiza el filtrado y guarda el archivo '.csv' en la ruta pasada como argumento (ruta_drive).


  Raises
  ------------
    - ValueError: Muestra un mensaje de error por pantalla en el caso de que el argumento 'valor_clasificacion' no sea válido para el DataFrame pasado como argumento
    - ValueError: En el caso de que no se pueda completar la descarga del archivo en la ruta especificada, imprime un mensaje de error por pantalla.

  """


  from google.colab import drive                                                         # Monta o se conecta a Google Drive para poder almacenar el archivo con extensión '.csv'
  drive.mount('/content/drive')

  dataframe = obtener_parametros_df (dataframe, nombres_columnas, verbose)               # Llama a la función 'obtener_parametros_df' para modificar el nombre de las columnas

  valores_validos = dataframe[nombres_columnas[1]].unique()                              # Crea un array de Numpy con los valores válidos para realizar el filtrado


  if valor_clasificacion not in valores_validos:                                         # Comprueba que el valor se encuentre dentro de los válidos, y sino muestra un error por pantalla
    raise ValueError (f"El valor de clasificación {valor_clasificacion} no está permitido. Inténtelo de nuevo con uno válido.")


  nombre_dataframe = "df_clasificacion_" + str(valor_clasificacion) + ".csv"             # Crea una variable con el nombre del archivo '.csv' en función del valor de filtrado

  dataframe = dataframe[dataframe[nombres_columnas[1]]==valor_clasificacion]             # Realiza la operación de filtrado por el 'valor_clasificacion' en sí misma


  try:                                                                                   # Intenta realizar el guardado del archivo que ha filtrado en la ruta especificada
    dataframe.to_csv(os.path.join(str(ruta_drive), str(nombre_dataframe)), index=False)  # Almacena el archivo con los valores filtrados en la ruta de Drive pasada como argumento

  except Exception as e:                                                                 # Si no es posible hacer la descarga del archivo, muestra un error por pantalla
    raise ValueError (f"No se ha podido completar la descarga del archivo con los valores filtrados. Inténtelo de nuevo. ")



"""# Función que descarga las señales de una determinada clase"""

def guardar_señales_valor (ruta_raiz_diccionarios, ruta_clasificacion, ruta_guardado):

  """
  Esta función guarda en un archivo  con extensión '.pkl' las señales de ECG que pertenezcan a una clase determinada. Esto se sabe porque aparece su identificador ("id)
  en un archivo con extensión '.csv'.
  Para ello, recorre múltiples diccionarios almacenados en carpetas y selecciona únicamente aquellas señales cuyo identificador ('id') se encuentra en el CSV de clasificación.

  Parámetros
  -------------
    - ruta_raiz_diccionarios (str): Ruta en la que se almacenan los distintos directorios en los que se encuentran los distintos diccionarios con las señales
    - ruta_clasificacion (str): Ruta en la que se encuentra el archivo CSV con los identificadores de las señales que pertenecen a dicha clase
    - ruta_guardado (str): Ruta en la que se va a almacenar el archivo con extensión '.pkl' con las señales de una determinada clase, una vez que se hayan filtrado.


  Return
  -------------
    - nuevo_dic (dict): Diccionario que contiene las señales y los valores numéricos de estas que pertenecen a una determinada clase.

  Raises
  -------------
    - ValueError: Si no es posible realizar la descarga del diccionario, muestra un mensaje de error por pantalla.


  """


  nuevo_dic = {}                                                       # Crea un diccionario vacío en el que se van a almacenar las señales de una determinada clase
  archivo_clasificacion = pd.read_csv(ruta_clasificacion)              # Carga el archivo con los valores de clasificación en el entorno de trabajo

  set_archivos_clasif = set(archivo_clasificacion["id"].unique())      # Extrae los identificadores de los archivos por su columna 'id'


  for i in os.listdir(ruta_raiz_diccionarios):                         # Recorre los distintos directorios que contienen señales de ECG
    ruta_carpeta = os.path.join(str(ruta_raiz_diccionarios), str(i))   # Crea una ruta a cada uno de los directorios de señales

    if os.path.isdir(ruta_carpeta):                                    # Comprueba que la ruta sea un directorio
      dic_señales = carga_archivos_entorno (ruta_carpeta)              # Carga en el entorno de trabajo los archivos que se encuentran en dicho directorio

      for e in dic_señales:                                            # Recorre los elementos del diccionario de señales que se ha cargado
        if e in set_archivos_clasif:                                   # En el caso de que alguno de estos archivos se encuentre también en el 'archivo_clasificacion' entra en el bucle
          nuevo_dic[e] = dic_señales[e]                                # Inicializa un nuevo elemento en el diccionario con la señal que pertenece a una determinada clase
  try:                                                                 # Intenta realizar el guardado del diccionario en la ruta especificada
    with open (ruta_guardado, "wb") as archivo:                        # Abre la ruta en que va a realizar el guardado en modo binario para escritura
      pickle.dump(nuevo_dic, archivo)                                  # Realiza el guardado del diccionario en la ruta especificada en formato pickle
      print ("Diccionario guardado correctamente en formato .pkl")     # Imprime un mensaje de confirmación de la descarga por pantalla

  except Exception as e:                                               # Si no es posible realizar la descarga del diccionario muestra un mensaje de error por pantalla
    raise ValueError (f" No se ha podido complementar la descarga del diccionario. Inténtalo de nuevo. ")

  return nuevo_dic                                                     # Devuelve el diccionario que contiene las señales de una determinada clase, el que se ha guardado

"""# Función que carga un diccionario en formato pickle con las señales de una clase"""

def carga_dic_pickle (ruta_diccionario):

  """
  Esta función realiza la carga de un diccionario en formato pickle desde la ruta especificada como argumento.

  Este diccionario contiene las señales y los valores numéricos de estas, que pertenecen a una determinada clase, es decir, las señales que han sido filtradas en función de su
  clase.

  Parámetros
  -------------
    - ruta_diccionario (str): Ruta a la dirección de Google Drive en que se encuentra el diccionario con las señales de una determinada clase en formato pickle

  Return
  -------------
    - diccionario (dict): Diccionario que contiene las señales y los valores numéricos de estas de una determinada clase.

  Raises
  -------------
    - ValueError: Si no es posible realizar la carga del diccionario, muestra un mensaje de error por pantalla.

  """


  try:                                                               # Intenta realizar la carga del diccionario desde la ruta especificada en Google Drive
    with open (ruta_diccionario, "rb") as archivo:                   # Abre la ruta en la que se encuentra el diccionario en modo binario para lectura
      diccionario = pickle.load (archivo)                            # Realiza la carga del diccionario desde la ruta especificada
      print (f"Diccionario cargado correctamente desde la ruta: {ruta_diccionario}")   # Imprime un mensaje de confirmación de la carga por pantalla

      return diccionario                                             # Devuelve el diccionario cargado

  except Exception as e:                                             # Si no es posible realizar la carga del diccionario muestra un mensaje de error por pantalla
    raise ValueError (f" No se ha podido complementar la carga del diccionario. Inténtalo de nuevo. ")