# -*- coding: utf-8 -*-
"""FuncionesCreacionRedGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0N_rrX0bHEYo_-VPmkCBCUg8cMuPN_g
"""

# Importación de las bibliotecas necesarias

import torch
import torch.nn as nn



"""# Función que crea el Generador (G) de la red"""

class Generador_CWGAN_GP_1D (nn.Module):

  def __init__(self, channels_noise, channels_img, features_g, num_classes, img_size, embed_size):

    """
    Esta función es el constructor de la clase Generador_CWGAN_GP_1D. Inicializa los atributos de este generador.

    Parámetros
    --------------
      - channels_noise: Número de canales del vector de ruido de entrada al generador.
      - channels_img: Número de canales de la señal de ECG de salida. En el caso de señales monoderivación, este es 1.
      - features_g: Número de base de filtros(canales) para las capas del generador.
      - num_classes: Número de clases diferentes en el conunto de datos (condiciones clínicas).
      - img_size: Tamaño de la señal de ECG de entrada, medido en número de puntos que la componen.
      - embed_size: Dimensión del espacio de embedding para las etiquetas de clase.

    Retorna
    --------------
      - None: La función no devuelve nada, sino que inicializa los atributos del generador.

    """



    super().__init__()                                                        # Llama al constructor de la clase base (nn.Module)
    self.img_size = img_size                                                  # Almacena el tamaño de la señal de ECG en un parámetro del constructor

    self.embedding = nn.Embedding(num_classes, embed_size)                    # Crea una capa de embedding que convierte las clases a tamaño fijo

    self.generador = nn.Sequential(                                           # Define una secuencia de capas para el generador
        self._block(channels_noise+embed_size, features_g * 16, 4, 1, 0),     # Concatena la señal de ruido con el embedding de las etiquetas
        self._block(features_g * 16, features_g * 8, 4, 2, 1),                # Reduce el número de canales del generador a la mitad
        self._block(features_g * 8, features_g * 4, 4, 2, 1),                 # Reduce el número de canales del generador a la mitad
        self._block(features_g * 4, features_g * 2, 4, 2, 1),                 # Reduce el número de canales del generador a la mitad
        self._block(features_g * 2, features_g, 4, 2, 1),                     # La señal de ruido comienza a parecerse a una señal de ECG real

        self._block(features_g, features_g // 2, 4, 2, 1),                    # La señal de ruido comienza a parecerse más a una señal de ECG real

        nn.ConvTranspose1d(features_g // 2, channels_img, kernel_size=4, stride=2, padding=1, output_padding=1), # Capa final de transposición convolucional para alcanzar los canales deseados
        nn.Tanh()                                                             # Activa la salida en el rango [-1, 1], útil para señales escaladas
    )





  def _block(self, in_channels, out_channels, kernel_size, stride, padding):
    """
    Esta función define un bloque auxiliar que crea capas convolucionales traspuestas para el generador, seguidas de un proceso de normalización y activación.

    Parámetros
    --------------
      - in_channels: Número de canales de entrada para esta capa.
      - out_channels: Número de canales de salida para esta capa.
      - kernel_size: Tamaño del kernel para la convolución.
      - stride: Paso de convolución.
      - padding: Relleno para la convolución.

    Retorna
    --------------
      - Una capa convolucional traspuesta con capas de normalización y activación.
    """

    return nn.Sequential(
        nn.ConvTranspose1d(in_channels, out_channels, kernel_size, stride, padding, bias=False,
        ),
        nn.BatchNorm1d(out_channels),
        nn.LeakyReLU (0.2),
    )


  def forward(self, input, etiquetas):
    """
    Esta función actúa como inferencia del generador.

    Parámetros
    ---------------
      - input:
      - etiquetas:

    Return
    ---------------
      - out:
    """
    temp = self.embedding(etiquetas)
    embedding = temp.unsqueeze(2)
    input = torch.cat([input, embedding], dim=1)
    out = self.generador(input)
    return out



"""# Función que crea el discriminador (D) de la red"""

class Discriminador_CWGAN_GP_1D (nn.Module):

  def __init__ (self, channels, features_d, num_classes, img_size):

    """
    Esta función inicializa la arquitectura del discriminador a partir de los parámetros especificados a tal efecto.

    Parámetros
    -------------
     - channels (int): Número de canales de entrada de la señal (para ECG 1D normalmente 1).
     - features_d (int): Número base de canales para la primera capa convolucional (controla la capacidad del modelo).
     - num_classes (int): Número de clases en el dataset, es decir, el número de condiciones clínicas presentes en él. En nuestro caso va a ser igual a 4
     - img_size (int): Longitud (número de muestras) de cada segmento de la señal.

    Return
    -----------
     - None: La función no devuelve nada, sino que inicializa los atributos del discriminador.

    """

    super().__init__()
    self.img_size = img_size

    self.embedding = nn.Embedding(num_classes, img_size)

    self.discriminador = nn.Sequential(
        nn.Conv1d(channels+1, features_d, kernel_size=4, stride=2, padding=1),
        nn.LeakyReLU(0.2),

        self._block(features_d, features_d * 2, 4, 2, 1),     # (features_in, features_out, kernel_size, stride, padding )
        self._block(features_d * 2, features_d * 4, 4, 2, 1),
        self._block(features_d * 4, features_d * 8, 4, 2, 1),


        nn.Conv1d(features_d * 8, 1, kernel_size=4, stride=2, padding=0, dilation=1),
    )

    self._initialize_fc_layer (channels)




  def _block(self, in_channels, out_channels, kernel_size, stride, padding):
    """
    Esta función constituye el bloque convolucional auxiliar con normalización e instancia y activación LeakyReLU para el discriminador.

    Parámetros
    --------------
      - in_channels (int): Canales de entrada del bloque.
      - out_channels (int): Canales de salida del bloque.
      - kernel_size, stride, padding: Parámetros del filtro convolucional.

    Return
    --------------
     - nn.Sequential: Bloque listo para ser encadenado en el discriminador.

      """
    return nn.Sequential(
        nn.Conv1d(in_channels, out_channels, kernel_size, stride, padding, bias=False),
        nn.InstanceNorm1d(out_channels, affine=True),
        nn.LeakyReLU(0.2)
    )

  def _initialize_fc_layer(self, channels):

    """
    Esta función inicializa la capa totalmente conectada (`self.fc`) calculando dinámicamenteel tamaño de la salida de la red convolucional a tal efecto.

    Esto es útil cuando el tamaño de entrada (`img_size`) puede variar.

    Parámetros
    --------------
      - channels (int): Número de canales de entrada de la señal (para ECG 1D normalmente 1).

    Return
    --------------
      - None: La función no devuelve nada, sino que inicializa la capa totalmente conectada (`self.fc`).

    """
    # Crear un tensor de prueba con batch_size=1, canales+embedding y img_size
    dummy_labels = torch.zeros(1, dtype=torch.long)
    dummy_input = torch.zeros(1, channels, self.img_size)
    dummy_embedding = self.embedding(dummy_labels).view(1, 1, self.img_size)
    dummy_input_cat = torch.cat([dummy_input, dummy_embedding], dim=1)

    with torch.no_grad():
      out = self.discriminador(dummy_input_cat)
      n_features = out.view(1, -1).shape[1]
    self.fc = nn.Linear(n_features, 1)

  def forward (self, input, etiquetas):

    """
    Esta función se encarga de la propagación hacia adelante del discriminador.

    Parámetros
    --------------
      - input (Tensor): Tensor de señales 1D con forma (batch_size, channels, img_size).
      - etiquetas (Tensor): Tensor de etiquetas (enteros) con forma (batch_size,).

    Return
    --------------
      - out (Tensor): Escalar por muestra del batch (forma: [batch_size, 1]), que representa la puntuación del discriminador para cada señal condicionada a su clase.

    """
    embedding = self.embedding(etiquetas).view(etiquetas.shape[0], 1, self.img_size)
    input = torch.cat([input, embedding], dim=1)

    out = self.discriminador(input)
    out = out.view(out.size(0), -1)
    out = self.fc(out)

    return out

