# -*- coding: utf-8 -*-
"""FuncionesPreprocesamientoDatos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bSVnn-U2EzJtF9xOBQTAF5kF5ZHmi5qC

#**Funciones que llevan a cabo el preprocesamiento inicial de los datos para poder trabajar con ellos en nuestra red GAN**

El orden que siguen estas funciones es el siguiente, realizando las distintas modificaciones:

1. Obtención de la señal numérica a partir de un objeto wfdb.Record. Esta es una matriz de NumPy.

2. Filtrado de la señal dentro de un rango de frecuencias.

3. Normalización de la señal y reescalado entre [-1, 1]

4. Segmentación de la señal en base al pico R del complejo QRS

5. Pipeline que combina todas las funciones de procesado anterior

6. Descarga de los registros una vez procesados
"""



# Importación de las bibliotecas necesarias para el correcto funcionamiento de las funciones

import numpy as np
import os
import matplotlib.pyplot as plt
import wfdb
from scipy.signal import butter, filtfilt, find_peaks



"""## Función que obtiene la matriz de NumPy con los valores numéricos de la señal


"""

def obtener_señal_ecg (record):

  """
  Esta función extrae la señal del objeto wfdb.Record, es decir, la matriz de NumPy que contiene los valores numéricos de la señal, que son los que realmente necesitamos para
  poder trabajar con ellos.

  Parámetros
  --------------
    - record(wfdb.Record): Objeto que contiene el objeto de tipo wfdb.Record de uno de los registros de nuestro dataset, el que indiquemos en este caso.

  Return
  --------------
    - señal unidimensional (np.array): Señal 1D extraída a partir del objeto wfdb.Record (matriz) aplanada y en formato de array de NumPy.

  Raises
  --------------
    - ValueError: Si el objeto de tipo wfdb.Record no contiene el atributo 'p_signal' o este es None se muestra por pantalla un mensaje de error.

  """

  if record.p_signal is not None:                           # Comprueba que el objeto wfdb.Record no sea nulo para extraer los valores numéricos de la señal
    señal = record.p_signal                                 # Se crea una variable interna con la matriz de NumPy que recoge los valores numéricos de la señal
    señal_unidimensional = señal.flatten()                  # Aplana la señal, convirtiéndola en un array de NumPy. Esto solo es posible para señales unidimensionales, como las nuestras.
    return señal_unidimensional                             # Devuelve los valores numéricos de la señal al usuario

  else:                                                     # Muestra un mensaje de error cuando no es posible acceder al atributo 'p_signal' porque nuestro Record no lo tiene
    raise ValueError("El objeto de tipo wfdb.Record no contiene el atributo 'p_signal' ")



"""## Función que realiza el filtrado de la señal dentro de un rango de frecuencias"""

def filtro_pasa_banda (record, lim_inf=0.5, lim_sup=40, orden=4):

  """
  La función aplica un filtro pasa banda de tipo Butterworth a la señal, para quedarse con las frecuencias deseadas, evitando así que el ruido u otros sonidos corporales puedan
  interferir en el resultado del entrenamiento. Es decir, filtra la señal dentro del rango de frecuencias deseado.

  Parámetros
  ------------
    - record (wfdb.Record): Objeto de tipo Record de uno de los registros de nuestro dataset, el cual contiene la señal a filtrar y la frecuencia de muestreo en el método '.fs'
    - lim_inf (float, optional): Frecuencia de corte inferior de la señal ECG. Si no indicamos nada, es 0.5 Hz por defecto
    - lim_sup (float, optional): Frecuencia de corte alta de la señal de ECG del objeto wfdb.Record. Tiene un valor por defecto de 40 Hz.
    - orden (int, optional): Indica el orden del filtro de Butterworth. Es 4 por defecto, a no ser que indiquemos otro valor para dicho filtro.



  Return
  ----------
    - señal_filtrada (np.array): Array de NumPy con la señal filtrada dentro de los rangos de frecuencia pasados como argumento a la señal.


  Raises
  ----------
    - ValueError: Mensaje de error que indica que los límites de filtrado no se encuentran dentro del rango válido para la frecuencia de Nyquist.


  """


  frec_ecg = record.fs                                           # Obtiene la frecuencia de muestreo a la que se ha grabado la señal de ECG
  señal_ecg_1d = obtener_señal_ecg(record)                       # Consigue el array de NumPy que contine la señal del objeto 'record' aplanada
  frec_nyquist = 0.5 * frec_ecg                                  # Calcula la frecuencia de Nyquist, lo cual es vital para evitar el proceso de 'aliasing'

  if lim_inf > 0 and lim_sup < frec_nyquist:                     # Comprueba si los límites (inferior y superior) cumplen con la frecuencia de Nyquist, para que el filtrado sea útil
    lim_inf_normal = lim_inf / frec_nyquist                      # Normaliza la frecuencia del límite inferior con respecto a la frecuencia de Nyquist, para poder aplicar el filtro
    lim_sup_normal = lim_sup / frec_nyquist                      # Normaliza la frecuencia del límite superior con respecto a la frecuencia de Nyquist, necesario para la función 'butter'

    coef_b, coef_a = butter(orden, [lim_inf_normal, lim_sup_normal], btype='band')     # Calcula los coeficientes necesarios para el filtrado en base a los argumentos pasados
    señal_filtrada = filtfilt(coef_b, coef_a, señal_ecg_1d)                            # Realiza el filtrado de la función mediante un filtro pasa banda de Butterworth

  else:                                                          # Se muestra un mensaje de error por pantalla cuando los coeficientes no cumplen con la frecuencia de Nyquist
    raise ValueError("Los límites del filtro deben estar dentro del rango de Nyquist.")

  return señal_filtrada                                          # Devuelve la señal (array de NumPy) una vez que ha sido filtrada dentro de los límites indicados en el argumento



"""## Funciones que llevan a cabo la normalización y escalado de la señal

### Función que calcula los parámetros globales del dataset para hacer la normalización Z - Score del dataset
"""

def obtener_param_globales (diccionario_dataset):

  """
  La función calcula tanto la media como la desviación estándar global para el dataset completo con el que vamos a trabajar.
  Esto es importante para llevar a cabo la normalización de las señales, presentando así todos los registros del diccionario la misma escala, mejorando así la consistencia
  estadística y la convergencia del modelo.

  Parámetros
  -------------
    - diccionario_dataset (dict): Diccionario en el que se encuentran todos los registros (objetos wfdb.Record) que conforman el dataset con el que vamos a trabajar


  Return
  ---------
    - media_global (float): Valor medio de las señales que componen el dataset con el que vamos a trabajar
    - desviacion_global (float): Desviación típica de los registros que conforman el set de datos que utilizamos


  Raises
  ----------
    - ValueError: Muestra un error por pantalla si el diccionario con los registros pasado como argumento no es realmente un diccionario o se encuentra vacío

  """


  if not diccionario_dataset:                                        # Muestra un error por pantalla si el diccionario pasado como argumento se encuentra vacío
    raise ValueError ("El diccionario está vacío. Inténtalo de nuevo.")

  lista_señales_1d = []                                              # Crea una lista en la que se van a almacenar las señales 1D de cada uno de los registros del diccionario
  for nom, record in diccionario_dataset.items():                    # Recorre cada uno de los registros / entradas del diccionario
    señal = obtener_señal_ecg(record)                                # Obtiene los valores numéricos de cada record con la función 'obtener_señal_ecg()' en un array de NumPy
    lista_señales_1d.append (señal)                                  # Añade este array a la lista creada para almacenar este tipo de dato

  señales_concatenadas = np.concatenate (lista_señales_1d)           # Concatena todos los valores numéricos de la lista, para calcular la media y la desviación de todos


  media_global = np.mean (señales_concatenadas)                      # Calcula la media global para todo el conjunto de registros del dataset
  desviacion_global = np.std (señales_concatenadas)                  # Calcula la desviación estándar del conjunto de datos del dataset

  return media_global, desviacion_global                             # Devuelve la media y desviación global del dataset, las cuales vamos a utilizar para el proceso de normalización



"""### Función para el proceso de normalización y escalado en sí mismo"""

def normalizar_señal (segmento, media_global, desviacion_global):

  """
  Esta función lleva a cabo el proceso de normalización de uno de los segmentos de tamaño fijo en que se divide una señal, utilizando para ello la media y la desviación global del
  dataset en el que se encuentra dicha señal, es decir, utiliza una segmentación de tipo Z-Score
  Es importante la universalidad de estos parámetros en el dataset para que todas las señales, y los segmentos en que se dividen estas, se encuentren en la misma escala, y poder
  así trabajar con ellas de forma más eficiente.
  Además, una vez realizada la normalización, realiza un reescalado de los datos, entre los valores -1 y 1. Esta modificación es necesaria para poder entrenar la red GAN que vamos
  a utilizar en el futuro.

  Parámetros
  -------------
    - segmento (np.array): Segmento de tamaño fijo en el que se ha dividido la señal, y el cual va a ser normalizado
    - media (float): Media global del dataset con el que vamos a trabajar
    - desviacion (float): Desviación típica global para el set de datos al que pertenece el segmento a normalizar


  Return
  ---------
    - segmento_normalizado (np.array): Segmento de tamaño fijo, resultado de dividir la señal, pero ya normalizado según los parámetros globales del dataset



  Raises
  ---------
    - ValueError: Muestra un error por pantalla si la desviación estándar es igual a cero, ya que esto quiere decir que no es posible llevar a cabo la normalización del segmento
  """

  if desviacion_global != 0:                                                # Comprueba que la desviación de la señal sea distinta de cero, para poder normalizar la señal
    segmento_normalizado = (segmento - media_global) / desviacion_global    # Realiza el proceso de normalización de la señal

    valor_minimo = np.min(segmento_normalizado)                             # Calcula la muestra de menor valor de la señal que estamos normalizando
    valor_maximo = np.max(segmento_normalizado)                             # Calcula el valor máximo de la señal que estamos normalizando
    segmento_escalado = 2 * (segmento_normalizado - valor_minimo) / (valor_maximo - valor_minimo) - 1      # Se realiza el proceso de escalado de la señal


    return segmento_escalado                                                # Devuelve el segmento concreto con el que estamos trabajando ya normalizado y escalado

  else:                                                                     # Muestra un error por pantalla si la desviación típica es igual a 0
    raise ValueError ("Para poder realizar el proceso de normalización la desviación debe ser distinta de 0. Inténtalo de nuevo.")



"""# Función que lleva a cabo la segmentación de la señal en base al pico R del complejo QRS"""

def segmentacion_complejo_qrs (señal , exponente=7, frec_muestreo = 300, distancia_minima = 0.25, altura_minima = None):

  """
  Esta función segmenta la señal unidimensional procedente de un ECG en fragmentos del mismo tamaño para con ellos entrenar una red GAN utilizando la biblioteca de NumPy.
  Para ello se emplea un detector de picos que va a detectar el pico R del complejo QRS en cada una de las señales de ECG que se dan a lo largo de un mismo registro. Una vez
  detectado el pico, se extiende el segmento hacia ambos lados en función del tamaño de las ventanas que se van a generar.
  Esta forma de segmentación va a asegurar que no se pierda información acerca de las señales de ECG de los registros, o que estas no se corten en la mitad, lo cual podría llegar
  a influir sobre los resultados del entrenamiento de la red GAN.

  Para que esta segmentación pueda tener lugar es necesario tener en cuenta que el tamaño de la ventana debe ser menor que la longitud de la propia señal, ya que lo contrario
  no es viable, porque no llegaríamos ni a poder obtener la primera ventana, así como que la señal del principio o del final no aparezca entera, es decir, que esté fragmentada.

  Parámetros
  -------------
    - señal (np.array): Señal unidimensional en forma de array de NumPy que contiene los valores numéricos de un objeto tipo wfdb.Record. Va a ser el objeto de la segmentación.
    - exponente = 7 (optional, int): Exponente para la potencia que va a determinar el tamaño de la ventana generada en función de una potencia en base 2: tamaño =  2^(potencia_n+1)+1.
    - frec_muestreo = 300 (optional, int): Frecuencia de muestreo de las señales de electrocardiograma. Esta se mide hercios (Hz).
    - distancia_minima = 0.25 (optional, float): Distancia mínima medida en segundos que debe darse entre los picos para que estos se consideren como tal.
    - altura_minima = None (optional, float): Altura mínima, en términos de amplitud, que debe presentar un pico para que el detector de picos lo considere como tal.
    En el caso de ser None, se emplea un valor relativo calculado a partir de los valores máximos y mínimos de la señal.


  Return
  -------------
    - segmentos_complejo_qrs (np.array): Array 2D que contiene cada uno de los segmentos en que se divide la señal centrados en el pico R del complejo QRS. Forma: [n_segmentos, tamaño_segmento]
    - indices_picos_validos (np.array): Array 1D que contiene los índices que representan a los picos R de estos segmentos en que se divide la señal.

  Raises
  -------------
    - ValueError: Se muestra un error por pantalla cuando la longitud de la ventana es mayor que el propio tamaño de la señal, ya que no es posible realizar la segmentación

  """


  segmentos_complejo_qrs = []                                   # Crea una lista vacía en la que se van a almacenar las ventanas en que se divide la señal
  indices_picos_validos = []                                    # Crea una lista vacía que va a almacenar los índices en que se encuentran los picos válidos


  señal_array = np.asarray (señal)                              # Convierte la señal a array 1D (aunque ya lo debería ser) para asegurarse de que es posible la segmentación


  tamaño_ventana = 2**(exponente+1) + 1                         # Calcula el número de muestras que van a componer la señal (debe ser impar para centrar la muestra del pico)

  if tamaño_ventana > len(señal):                               # En el caso de que el tamaño de la ventana sea mayor que la propia longitud de la señal, lanza un mensaje de error.
    raise ValueError ("La longitud de la ventana debe ser menor que la longitud de la propia señal. Inténtalo de nuevo.")

  muestras_lateral = tamaño_ventana // 2                        # Calcula el número de muestras que van a ir a cada lado del pico, es decir, los laterales


  distancia_picos = int(distancia_minima * frec_muestreo)       # Calcula la distancia mínima en número de muestras que debe haber entre dos picos para considerarlos como tal


  if altura_minima is None:                                     # Entra en el bucle cuando no se ha pasado como argumento la altura mínima que debe tener un pico para considerarlo así
    altura_max_señal = np.max (señal_array)                     # Calcula la altura máxima de la señal con la que está trabajando
    altura_min_señal = np.min (señal_array)                     # Calcula la altura mínima de la señal con la que trabaja
    rango_señal = altura_max_señal - altura_min_señal           # Calcula el rango de la señal, es decir, la diferencia entre su valor máximo y mínimo
    altura_pico = 0.2 * rango_señal                             # Calcula la altura mínima que debe tener un pico para considerarlo como tal y diferenciarlo de otros o de ruido

  else:                                                         # En caso de no cumplirse la condición propuesta se entra en el siguiente bloque de código
    altura_pico = altura_minima                                 # Asigna la 'altura_minima' pasada como argumento a la variable con la altura mínima para que un pico se considere así


  prominence_señal = 0.2 * rango_señal                          # Calcula la prominencia de la señal en base a su valor escalado entre [-1, 1]
  indices_picos, propiedades = find_peaks (señal_array, height = altura_pico, distance = distancia_picos, prominence=prominence_señal)     # Realiza la detección de picos en base a las variables calculadas


  for i in indices_picos:                                       # Recorre la lista que contiene los índices numéricos de los picos de la señal
    inicio_ventana = i - muestras_lateral                       # Calcula el índice numérico de la señal que corresponde a la muestra del inicio del pico
    fin_ventana = i + muestras_lateral + 1                      # Calcula el índice en el que finaliza la ventana correspondiente


    if inicio_ventana < 0 or fin_ventana > len (señal_array):   # Evita crear ventanas al inicio o al final de la señal, para que los picos aparezcan completos en todas ellas
      continue                                                  # En el caso de que se de este evento pasa al siguiente elemento de 'indices_picos'

    ventana_indiv = señal_array[inicio_ventana:fin_ventana]     # Crea un array con las muestras numéricas que se encuentran en el rango de la ventana
    segmentos_complejo_qrs.append (ventana_indiv)               # Añade este segmento a una lista con todas las ventanas en que se ha dividido la señal actual
    indices_picos_validos.append (i)                            # Añade este índice a la lista en que se almacenan los picos que corresponden a ventanas válidas


  if len(segmentos_complejo_qrs) == 0:
    print("No se han encontrado picos válidos en la señal. Esta es muy corta o no presenta picos. Inténtalo de nuevo.")
    return None, None

  segmentos_complejo_qrs = np.array (segmentos_complejo_qrs)    # Convierte la lista con los valores numéricos de los segmentos en un array de NumPy
  indices_picos_validos = np.array (indices_picos_validos)      # Transforma la lista en que se almacenan los índices del pico R en un array de NumPy


  return segmentos_complejo_qrs, indices_picos_validos          # Devuelve el array con las ventanas creadas y el que almacena los índices de los picos válidos



"""# Funciones de procesamiento de las señales que incluyen todas las funciones de preprocesamiento anteriores

## Función de procesamiento de un registro individual
"""

def procesar_record_individual (record, mean_global, std_global, exp=7, fs = 300, dis_min = 0.25, alt_min = None, corte_bajo = 0.5, corte_alto = 40, ord = 4):

  """
  Esta función combina todas las funciones previamente definidas, con el objetivo de llevar a cabo un preprocesamiento de la señal de un record individual de un dataset de ECG y
  poder entrenar una red GAN con señales de este tipo. Para ello, se obtiene la señal (valores numéricos), se aplica un filtro pasa banda, se segmenta en ventanas de un tamaño
  fijo y se normaliza en base a la media y a la desviación típica global del dataset.


  Parámetros
  --------------
    - record (wfdb.Record): Objeto de tipo wfdb.Record que equivale a uno de nuestros registros del dataset, y el cual contiene la señal de ECG y la frecuencia de muestreo de la misma
    - mean_global (float): Media universal de todos los valores de las señales que conforman la totalidad del dataset. Esta se calcula para la totalidad del dataset
    - std_global (float): Desviación típica calculada a partir de todas las señales que contiene el set de datos de trabajo. Esta se calcula en base a todo el dataset
    - exp (optional, int): Exponente que va a determinar el tamaño de las ventanas en que se dividen las señales por una potencia en base 2
    - fs (optional, int): Frecuencia de muestreo de la señal que se va a procesar
    - dis_min (optional, float): Distancia mínima (en segundos) para que se identifiquen dos picos como independientes
    - alt_min (optional, float): Altura mínima (en unidades de amplitud) para que se identifiquen dos picos como independientes
    - corte_bajo (optional, float): Frecuencia mínima (Hz) que se va a mantener como parte de la señal en el proceso de filtado pasa banda que se va a llevar a cabo
    - corte_alto (optional, floar): Frecuencia máxima (Hz) que el filtrado pasa banda va a permitir conservar como valor numérico de la señal procesada
    - ord (optional, int): Orden del filtro Butterworth aplicado como parte del filtro pasa banda

  Return
  --------------
    - segmentos_procesados (list): Lista que contiene los arrays de NumPy que almacenan la señal procesada en cada uno de los segmentos generados

  Raises
  --------------
    - ValueError: Muestra un mensaje de error por pantalla en el caso de que no sea posible acceder a la señal del objeto wfdb.Record pasado como argumento a la función
    - ValueError: Muestra un mensaje de error por pantalla en el caso de que no sea posible realizar la segmentación de la señal
   """

  segmentos_procesados = []                                       #Inicialización de la lista en la que se van a almacenar los arrays de cada uno de los segmentos una vez procesados

  try:                                                            #Intenta extraer los valores numéricos a partir de la señal
    señal_ecg = obtener_señal_ecg (record)                        #Extracción de la señal del objeto wfdb.Record pasado como argumento a la función

  except ValueError as e:                                         # En el caso de que no se pueda acceder a la señal del objeto wfdb.Record, se muestra un mensaje de error por pantalla
    print(f"Error extrayendo señal: {e}")
    return None                                                   # En el caso de que no se pueda acceder a la señal, se devuelve el conjunto vacío

  if señal_ecg.size == 0:                                         #Comprueba que la señal no sea nula
      print(f"La señal se encuentra vacía, por lo que no se puede llevar a cabo el procesamiento.")  # Muestra un mensaje de error por pantalla
      return None                                                 # En el caso de encontrarse vacía, la función devuelve el conjunto vacío

  else:                                                           # En el caso de que la señal no se encuentre vacía pasa al resto de pasos del preprocesamiento
    señal_filtrada = filtro_pasa_banda (record, lim_inf=corte_bajo, lim_sup =corte_alto, orden = ord)    #Aplicación del filtro pasa banda a la señal que ha sido extraída

    try:                                                          # Intenta realizar la segmentación de la señal
        segmentos, indices_picos = segmentacion_complejo_qrs(señal_filtrada, exponente=exp, frec_muestreo=fs, distancia_minima=dis_min, altura_minima=alt_min) # Segmentación de la señal en función del complejo QRS

    except ValueError as e:                                       # En el caso de que no se pueda realizar la segmentación porque de error, detiene el proceso de segmentación
        print(f"No se pudo segmentar la señal: {e}. No obtenemos picos en la misma.")   # Muestra un mensaje de error por pantalla
        return None                                               # Devuelve el conjunto vacío

    for i in segmentos:                                           # Recorrido cada uno de los valores / muestras que componen los segmentos en que se ha dividido la señal
      segm_proc = normalizar_señal (i, mean_global, std_global)   # Normalización de cada uno de los segmentos en base a la media y desviación global del dataset
      segmentos_procesados.append (segm_proc)                     # Adición del segmento normalizado a la lista vacía que se ha creado para su almacenamiento

    segmentos_procesados = np.array (segmentos_procesados)        # Convierte la lista con los segmentos en un array de NumPy

  return segmentos_procesados                                     # Devolución de todos los segmentos de la señal filtrados y normalizados



"""## Función que lleva a cabo el procesado de todos los registros del dataset"""

def procesar_multiples_registros (diccionario_registros, exp=7, fs = 300, dis_min = 0.25, alt_min = None, lim_inf = 0.5, lim_sup=40, ord = 4):

  """
  La función se encarga de realizar el procesamiento de las señales de la totalidad de registros de un dataset. Este se pasa como argumento a la función en forma de diccionario.
  Para llevar a cabo esta modificación se va a realizar la modificación individual de cada uno de estos registros, obteniendo su señal, filtrándolos, realizando una segmentación
  con solapamiento y normalizando los mismos con la media y la desviación típica del dataset de trabajo.

  Este procesamiento es esencial para preparar las señales de ECG, como es nuestro caso, para poder entrenar modelos de aprendizaje automático, como son las redes GAN, ya que
  este proceso va a mejorar su eficacia y robustez.

  Parámetros
  ---------------
    - diccionario_registros (dict): Diccionario que contiene todos los obejtos de tipo wfdb.Record que conforman el dataset de trabajo
    - exp (optional, int): Exponente que va a determinar el tamaño de las ventanas en que se dividen las señales por una potencia en base 2.
    - fs (optional, int): Frecuencia de muestreo de la señal que se va a procesar.
    - dis_min (optional, float): Distancia mínima (en segundos) para que se identifiquen dos picos como independientes.
    - alt_min (optional, float): Altura mínima (en unidades de amplitud) para que se identifiquen dos picos como independientes.
    - lim_inf (float, optional): Límite inferior de frecuencia (Hz) que se va a incluir como parte de la señal filtrada
    - lim_sup (float, optional): Valor máximo de frecuencia (Hz) que va a pasar el filtro pasabanda aplicado a la señal
    - ord (int, optional): Orden del filtro de Butterworth aplicado a la señal


  Return
  ---------------
    - segmentos_diccionario (list): Lista aplanaza que contiene la señal normalizada de cada uno de los segmentos en que se han dividido las señales del diccionario


  Raises
  --------------
    - ValueError: Muestra un mensaje de error por pantalla en el caso de que algún objeto wfdb.Record no se haya podido procesar correctamente

  """

  segmentos_diccionario = []                                            # Se crea una lista vacía en la que se van a almacenar los segmentos de las señales correspondientes procesadas

  media, desviacion = obtener_param_globales (diccionario_registros)    # Se obtienen tanto la media como la desviación estándar global para el diccionario de las señales


  for nombre, record in diccionario_registros.items():                  # Recorre todas las señales que se encuentran almacenadas en el diccionario
    try:                                                                # Intenta llevar a cabo un preprocesamiento individual sobre cada señal del diccionario
      segmentos_record = procesar_record_individual (record, media, desviacion, exp=exp, fs = fs, dis_min = dis_min, alt_min = alt_min, corte_bajo = lim_inf, corte_alto= lim_sup, ord = ord)
      if segmentos_record is not None:                                  # Entra en el bucle en el caso de que se haya obtenido una lista de segmentos a partir de la señal
        segmentos_diccionario.extend (segmentos_record)                 # Añade a la lista los segmentos procesados del registro individual

      else:                                                             # Entra en el bucle en el caso de que no haya obtenido una lista con los segmentos correspondientes
        print(f"El registro {nombre} no pudo ser procesado y fue omitido.")   # Muestra un mensaje de error por pantalla indicando que se ha omitido dicha señal sin segmentos


    except Exception as e:                                              # Muestra un mensaje de error por pantalla indccando que no se ha podido procesar el registro individaul
      raise ValueError (f"Se ha obtenido un error procesando el record {nombre}. Inténtalo de nuevo.")

  return segmentos_diccionario                                          # Devuelve la lista en que se encuentran almacenados los segmentos en que se han dividido las señales del diccionario

"""# Función de descarga de los registros procesados"""

def descargar_segmentos_procesados (array_segmentos, ruta, nombre):

  """
  Realiza la descarga del array 2D con los segmentos normalizados en los que se han dividido las señales monocanales que integran el dataset.
  Este array presenta la forma [número_segmentos, tamaño_ventana], ya que todos estos segmentos van a presentar la misma longitud, igual al tamaño de ventana especificado a la
  hora de la creación de los mismos.

  La descarga se va realizar en Google Drive, en la ruta especificada como argumento de la función y bajo el nombre y extensión deseado por el usuario.

  Parámetros
  ----------------
    - array_segmentos (np.array): Array 1D que contiene todos los segmentos filtrados y normalizados en los que se han dividido las señales del dataset de trabajo

    - ruta (str): Ruta de Google Drive en la que se desea guardar dichos segmentos
      Ejemplo: '/content/drive/MyDrive/dataset_ECG/challenge2017/entrenamiento_GAN'

    - nombre (str): Nombre y extensión del archivo que se va a guardar en la ruta especificada
      Ejemplo: 'segmentos_ecg_procesados.npy'

  Return
  ----------------
    - None: Esta función no devuelve nada, ya que realiza el guardado de los segmentos en la dirección de Google Drive especificada

  Raises
  ----------------
    - ValueError: Se muestra un error por pantalla en el caso de que no sea posible realizar la descarga del array del dataset en la ruta o con el nombre especificado

  """

  from google.colab import drive                                         # Importa la biblioteca de Google Drive dentro de la función para poder conectarse a él
  drive.mount('/content/drive')                                          # Conecta el entorno de trabajo con Google Drive para poder almacenar los archivos pertinentes

  array_2d_segmentos = np.array(array_segmentos)                         # Convierte el array 1D en uno bidimensional del tipo [num_segmentos, tamaño_ventana]
  ruta_almacenamiento = ruta                                             # Crea una variable interna con la ruta en la que se quiere almacenar el array 2D creado

  os.makedirs (ruta_almacenamiento, exist_ok=True)                       # Crea el directorio especificado como argumento en el caso de que este no exista

  nombre_archivo = nombre                                                # Crea una variable interna con el nombre y extensión que se desea proporcionar al archivo con los segmentos

  ruta_completa = os.path.join (ruta_almacenamiento, nombre_archivo)     # Crea una variable con la ruta completa en la que se va a almacenar el archivo correspondiente

  try:                                                                   # Intenta realizar el guardado del array bidimensional en la ruta completa creada
    np.save (ruta_completa, array_2d_segmentos)
    print (f"Los segmentos procesados han sido guardados correctamente en la ruta {ruta_completa}.")   # Muestra un mensaje por pantalla en el caso de que consiga hacerlo

  except Exception as e:                                                 # Muestra un mensaje de error por pantalla en el caso de que no sea posible realizar la descarga
    raise ValueError ("Ha ocurrido un error y no se ha podido guardar correctamente el array que contiene los segmentos procesados. Inténtalo de nuevo.")