# -*- coding: utf-8 -*-
"""FuncionesDatosGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OwmGRWUd_9N2fkfDqnGTQa3MfQggKOS
"""

# Importación de las bibliotecas necesarias

import sys
import os
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader



"""#  Función que crea el dataset de entrenamiento"""

def creacion_dataset_GAN(ruta_drive, dict_etiquetas):
  """
  Esta función carga múltiples archivos .npy (uno por clase) desde una ruta especificada y los combina
  en un único conjunto de datos y etiquetas, que será usado para entrenar una red GAN.

  Parámetros
  ----------
  ruta_drive : str
      Ruta base en la que se encuentran almacenados los archivos .npy de cada clase.
      Cada archivo debe tener el nombre del identificador de clase seguido de ".npy".

  dict_etiquetas : dict
      Diccionario que asigna a cada nombre de archivo (sin la extensión) una etiqueta numérica.
      Por ejemplo: {"N": 0, "A": 1}

  Returns
  -------
  datos_GAN : np.ndarray
      Array 2D o 3D con todos los segmentos cargados, apilados verticalmente.

  etiquetas_GAN : np.ndarray
      Array 1D de enteros con la etiqueta correspondiente a cada segmento de datos.
  """

  datos = []      # Lista para almacenar los arrays de cada clase
  etiquetas = []  # Lista para almacenar las etiquetas correspondientes

  # Itera por cada clase representada en el diccionario
  for i, j in dict_etiquetas.items():
    ruta_dic = str(ruta_drive + "/" + str(i) + ".npy")  # Construye la ruta completa al archivo .npy
    segmentos_clase = np.load(ruta_dic)                # Carga el archivo como un array de numpy

    datos.append(segmentos_clase)                      # Añade los segmentos de esta clase a la lista de datos
    etiquetas.append(np.full(len(segmentos_clase), j)) # Crea un array con la etiqueta correspondiente y lo añade

  datos_GAN = np.vstack(datos)                         # Apila todos los arrays verticalmente (concatena por filas)
  etiquetas_GAN = np.concatenate(etiquetas)            # Concatena las etiquetas en un único array plano

  return datos_GAN, etiquetas_GAN                      # Devuelve los arrays para entrenar la GAN



"""# Función que crea la clase que va a manejar el dataset de entrenamiento"""

class ECGDataset(Dataset):
  """
  Clase personalizada para representar un dataset de señales ECG segmentadas,
  compatible con PyTorch y su DataLoader.

  Esta clase convierte los datos de entrada (segmentos y etiquetas) en tensores
  y permite indexarlos como un conjunto de datos estándar.

  Parámetros
  ----------
  segmentos : array-like o np.ndarray
      Array con las señales segmentadas, típicamente de forma (N, L), donde N es
      el número de segmentos y L la longitud de cada uno.

  etiquetas : array-like o np.ndarray
      Array con las etiquetas correspondientes a cada segmento, típicamente enteros.

  Métodos
  -------
  __len__() :
      Devuelve la cantidad total de segmentos en el dataset.

  __getitem__(idx) :
      Devuelve el segmento y su etiqueta correspondiente en el índice `idx`.
  """

  def __init__(self, segmentos, etiquetas):
    # Convierte los arrays de entrada en tensores de PyTorch
    self.segmentos_reales = torch.tensor(segmentos, dtype=torch.float32)  # Señales como float32
    self.etiquetas_reales = torch.tensor(etiquetas, dtype=torch.long)     # Etiquetas como enteros largos (recomendado para clasificación)

  def __len__(self):
    # Devuelve la longitud total del dataset
    longitud_dataset = len(self.segmentos_reales)
    return longitud_dataset

  def __getitem__(self, idx):
    # Extrae el segmento en la posición `idx`, añadiendo un canal ficticio (dimensión 1)
    datos_registro = self.segmentos_reales[idx].unsqueeze(0)  # (L,) -> (1, L)
    etiqueta_registro = self.etiquetas_reales[idx]            # Etiqueta como escalar

    return datos_registro, etiqueta_registro



"""# Función que crea el objeto dataloader a partir del dataset"""

def creacion_dataloader(datos, etiquetas, batch_size=64, shuffle=True):
  """
  Crea un objeto DataLoader de PyTorch a partir de señales segmentadas y sus etiquetas.

  Esta función toma los datos ya procesados y etiquetados, construye un dataset personalizado
  (usando la clase ECGDataset) y lo envuelve en un DataLoader, que permite el acceso
  por lotes durante el entrenamiento de modelos.

  Parámetros
  ----------
  datos : array-like o np.ndarray
      Array que contiene los segmentos de señales ECG. Debe ser de tipo float y
      con forma (N, L), donde N es el número de segmentos y L la longitud de cada uno.

  etiquetas : array-like o np.ndarray
      Array que contiene las etiquetas correspondientes a cada segmento. Deben ser enteros.

  batch_size : int, opcional (default=64)
      Tamaño de cada lote que será entregado durante el entrenamiento o evaluación.

  shuffle : bool, opcional (default=True)
      Indica si se deben barajar aleatoriamente los datos antes de cada época.

  Retorna
  -------
  dataloader : torch.utils.data.DataLoader
      Objeto DataLoader que proporciona lotes de datos durante el entrenamiento o evaluación.
  """

  # Se crea un dataset personalizado a partir de los datos y etiquetas
  dataset_GAN = ECGDataset(datos, etiquetas)

  # Se construye el DataLoader con el tamaño de lote y barajado especificados
  dataloader = DataLoader(dataset_GAN, batch_size=batch_size, shuffle=shuffle)

  # Se devuelve el DataLoader listo para ser utilizado
  return dataloader

