# -*- coding: utf-8 -*-
"""FuncionesEntrenamientoGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aPVyVZEceCHbJeiO47PglrHpqML2_Zb
"""

# Importamos las bibliotecas necesarias

import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import torch
import matplotlib.pyplot as plt
import numpy as np
import torch.autograd as autograd
import os
import sys

# Nos conectamos a Google Drive para poder cargar el archivo con las funciones

from google.colab import drive
drive.mount('/content/drive')

# Añadimos la ruta en la que se encuentra el archivo con extensión '.py'

sys.path.append('/content/drive/MyDrive/programacion_ECG')

# Importamos las funciones necesarias desde los otros módulos para poder

from funcionescreacionredgan import *
from funcionesentrenamientogan import *

"""## Entrenamiento de la red GAN

## Funciones de entrenamiento

### Función que inicializa los pesos de la función
"""

def inicializacion_pesos (model):
  """
  Inicializa los pesos de los distintos módulos de una red neuronal de forma específica,
  siguiendo una estrategia recomendada para redes GAN (por ejemplo, DCGAN).

  La función recorre todos los submódulos del modelo (capas convolucionales, lineales
  y de normalización) e inicializa sus parámetros según el tipo:

  - nn.Conv1d / nn.ConvTranspose1d:
    - Pesos: distribución normal con media 0 y desviación estándar 0.02.
    - Sesgos: constantes a 0 (si existen).

  - nn.BatchNorm1d:
    - Pesos (gamma): distribución normal con media 1 y desviación estándar 0.02.
    - Sesgos (beta): constantes a 0.

  - nn.Linear:
    - Pesos: distribución normal con media 0 y desviación estándar 0.02.
    - Sesgos: constantes a 0 (si existen).

  Parámetros
  --------------
    - model (nn.Module): Modelo de red neuronal cuyo conjunto de módulos internos se desea inicializar.

  Return
  ----------
    None: La función no devuelve ningún valor. Modifica los pesos del modelo directamente.

  """
  for i in model.modules():
    if isinstance(i, (nn.Conv1d, nn.ConvTranspose1d)):
      nn.init.normal_(i.weight.data, 0.0, 0.02)
      if i.bias is not None:
        nn.init.constant_(i.bias.data, 0)

    elif isinstance(i, nn.BatchNorm1d):
      nn.init.normal_(i.weight.data, 1.0, 0.02)
      nn.init.constant_(i.bias.data, 0)

    elif isinstance(i, nn.Linear):
      nn.init.normal_(i.weight.data, 0.0, 0.02)
      if i.bias is not None:
        nn.init.constant_(i.bias.data, 0)



"""### Función que inicializa los optimizadores del modelo de red GAN"""

def creacion_optimizadores(generador, discriminador, lr=1e-4, beta1=0.0, beta2=0.9):
    """
    Crea y devuelve los optimizadores Adam para el generador y el discriminador
    de una red GAN, utilizando parámetros de configuración típicos de redes
    como WGAN-GP o cWGAN-GP.

    Parámetros
    ----------
    generador : nn.Module
        Modelo generador cuya red se entrenará mediante el optimizador.

    discriminador : nn.Module
        Modelo discriminador cuya red se entrenará mediante el optimizador.

    lr : float, opcional (por defecto = 1e-4)
        Tasa de aprendizaje (learning rate) para ambos optimizadores.

    beta1 : float, opcional (por defecto = 0.0)
        Primer parámetro beta del optimizador Adam (controla el decaimiento de la media de los gradientes).

    beta2 : float, opcional (por defecto = 0.9)
        Segundo parámetro beta del optimizador Adam (controla el decaimiento de la varianza de los gradientes).

    Return
    ------
    optim_generador : torch.optim.Adam
        Optimizador Adam configurado para el generador.

    optim_discriminador : torch.optim.Adam
        Optimizador Adam configurado para el discriminador.
    """
    betas = (beta1, beta2)
    optim_generador = optim.Adam(generador.parameters(), lr=lr, betas=betas)
    optim_discriminador = optim.Adam(discriminador.parameters(), lr=lr, betas=betas)

    return optim_generador, optim_discriminador



"""### Función que calcula el valor de gradiente de penalti"""

def gradient_penalty(discriminador, etiquetas, señal_real, señal_fake, device="cpu"):
    """
    Calcula el término de penalización por gradiente (Gradient Penalty) utilizado en el
    entrenamiento de redes WGAN-GP o cWGAN-GP, con el objetivo de imponer la condición
    de Lipschitz en el discriminador.

    Este término fuerza al discriminador a tener un gradiente de norma cercana a 1
    sobre interpolaciones entre muestras reales y generadas, mejorando así la estabilidad
    del entrenamiento.

    Parámetros
    ----------
    discriminador : nn.Module
        El modelo discriminador al que se le aplicará la penalización por gradiente.

    etiquetas : Tensor
        Tensor con las etiquetas de clase correspondientes a las señales reales y falsas.
        Tiene forma (batch_size,).

    señal_real : Tensor
        Tensor con las señales reales del dataset. Forma: (batch_size, canales, longitud).

    señal_fake : Tensor
        Tensor con las señales generadas por el generador (falsas). Misma forma que `señal_real`.

    device : str, opcional (por defecto = "cpu")
        Dispositivo donde se realizarán los cálculos ('cpu' o 'cuda').

    Return
    ------
    penalty : Tensor
        Escalar que representa el valor medio de la penalización por gradiente para el batch actual.
    """
    batch_size, canales, len = señal_real.shape

    # Creamos un coeficiente de interpolación aleatorio epsilon
    epsilon = torch.rand((batch_size, 1, 1), device=device).repeat(1, canales, len)

    # Interpolamos entre la señal real y la generada
    img_interpolada = señal_real * epsilon + señal_fake * (1 - epsilon)
    img_interpolada = img_interpolada.to(device).requires_grad_(True)

    # Pasamos la señal interpolada por el discriminador
    pred_interpolada = discriminador(img_interpolada, etiquetas)

    # Creamos un tensor de salida con unos para calcular el gradiente
    salida_grad = torch.ones_like(pred_interpolada)

    # Calculamos el gradiente de la salida respecto a la entrada interpolada
    gradiente = torch.autograd.grad(
        outputs=pred_interpolada,
        inputs=img_interpolada,
        grad_outputs=salida_grad,
        create_graph=True,
        retain_graph=True
    )[0]

    # Aplanamos el gradiente por muestra
    gradiente = gradiente.view(gradiente.shape[0], -1)

    # Calculamos la norma L2 del gradiente
    gradiente_norm = gradiente.norm(2, dim=1)

    # Calculamos el término de penalización (deseamos que la norma ≈ 1)
    penalty = torch.mean((gradiente_norm - 1) ** 2)

    return penalty



"""### Creación de la función de pérdida para el generador"""

def funcion_perdida_generador(discriminador, etiquetas, señal_fake):
    """
    Calcula la función de pérdida para el generador en una red WGAN-GP
    (Wasserstein GAN con penalización por gradiente).

    En WGAN, el generador busca maximizar la puntuación que el discriminador asigna
    a las muestras falsas (señal_fake), lo cual equivale a minimizar el valor negativo
    de dicha puntuación media.

    Parámetros
    ----------
    discriminador : nn.Module
        Modelo discriminador que evalúa la "realidad" de las señales generadas.

    etiquetas : Tensor
        Tensor de etiquetas de clase correspondientes a cada muestra generada
        (forma: [batch_size]).

    señal_fake : Tensor
        Tensor con las señales generadas por el generador
        (forma: [batch_size, canales, longitud]).

    Return
    ------
    valor_perdida : Tensor
        Escalar que representa la pérdida del generador para el batch actual.
        Cuanto menor, mejor engaña el generador al discriminador.
    """
    pred_fake = discriminador(señal_fake, etiquetas)
    valor_perdida = - pred_fake.mean()
    return valor_perdida



"""### Creación de la función de pérdida para el discriminador"""

def funcion_perdida_discriminador(discriminador, etiquetas, señal_real, señal_fake, device="cpu", lambda_gp=10):
    """
    Calcula la función de pérdida para el discriminador en una arquitectura WGAN-GP
    (Wasserstein GAN con penalización por gradiente).

    Esta función combina tres términos:
    - La puntuación promedio que el discriminador asigna a las señales reales (que se desea maximizar).
    - La puntuación promedio que asigna a las señales falsas (que se desea minimizar).
    - La penalización por gradiente (Gradient Penalty), que impone la condición de Lipschitz.

    Parámetros
    ----------
    discriminador : nn.Module
        Modelo discriminador encargado de evaluar si una señal es real o generada.

    etiquetas : Tensor
        Tensor con las etiquetas de clase asociadas a las señales
        (forma: [batch_size]).

    señal_real : Tensor
        Tensor con las señales reales del dataset
        (forma: [batch_size, canales, longitud]).

    señal_fake : Tensor
        Tensor con las señales generadas por el generador
        (forma: [batch_size, canales, longitud]).

    device : str, opcional (por defecto = "cpu")
        Dispositivo sobre el que se realizan los cálculos ('cpu' o 'cuda').

    lambda_gp : float, opcional (por defecto = 10)
        Peso que regula la importancia del término de penalización por gradiente.

    Return
    ------
    valor_perdida : Tensor
        Escalar que representa el valor de la pérdida del discriminador para el batch actual.
        Este valor se minimiza durante el entrenamiento.
    """
    # Evaluación de señales reales
    pred_real = discriminador(señal_real, etiquetas)

    # Evaluación de señales falsas (sin afectar al generador)
    señal_fake_detach = señal_fake.detach()
    pred_fake = discriminador(señal_fake_detach, etiquetas)

    # Cálculo del término de penalización por gradiente
    g_p = gradient_penalty(discriminador, etiquetas, señal_real, señal_fake_detach, device)

    # Pérdida total del discriminador (se desea minimizar)
    valor_perdida = pred_fake.mean() - pred_real.mean() + lambda_gp * g_p

    return valor_perdida



"""# Función que lleva a cabo el proceso de entrenamiento"""

def entrenar_cwgan_gp(generador, discriminador, dataloader, optim_generador, optim_discriminador,
                      device, epochs=100, dim_noise=100, lambda_gp=10, critic_iter=5, verbose=True):
    """
    Función principal de entrenamiento para una red GAN condicional con penalización de gradiente (cWGAN-GP)
    aplicada a señales 1D, como las señales ECG.

    Se entrena alternativamente un discriminador (o "critic") y un generador en función de los principios de la
    WGAN-GP (Wasserstein GAN con Gradient Penalty), permitiendo una generación más estable de datos sintéticos.

    Parámetros
    ----------
    generador : nn.Module
        Modelo generador que toma ruido y etiquetas como entrada y genera señales sintéticas.

    discriminador : nn.Module
        Modelo discriminador que evalúa si una señal (real o generada) es auténtica, condicionada a su etiqueta.

    dataloader : DataLoader
        Objeto iterable que proporciona lotes de datos reales y sus correspondientes etiquetas.

    optim_generador : torch.optim.Optimizer
        Optimizador para actualizar los pesos del generador.

    optim_discriminador : torch.optim.Optimizer
        Optimizador para actualizar los pesos del discriminador.

    device : str
        Dispositivo de cómputo ('cpu' o 'cuda') donde se ejecutará el entrenamiento.

    epochs : int, opcional (por defecto = 100)
        Número total de épocas (iteraciones completas sobre el dataset) para entrenar la red.

    dim_noise : int, opcional (por defecto = 100)
        Dimensión del vector de ruido que alimenta al generador.

    lambda_gp : float, opcional (por defecto = 10)
        Peso del término de penalización por gradiente en la función de pérdida del discriminador.

    critic_iter : int, opcional (por defecto = 5)
        Número de actualizaciones del discriminador por cada actualización del generador.

    verbose : bool, opcional (por defecto = True)
        Si se activa, se imprimen métricas de entrenamiento cada 100 batches.

    Return
    ------
    None
        La función entrena los modelos y guarda sus pesos finales como archivos `.pth` en el directorio actual.
    """

    # Enviar modelos al dispositivo
    generador.to(device)
    discriminador.to(device)

    # Poner modelos en modo entrenamiento
    generador.train()
    discriminador.train()

    print("En este momento comienza el entrenamiento de la red GAN:")

    for i in range(epochs):
        for j, (señal_real, etiquetas) in enumerate(dataloader):
            current_batch_size = señal_real.size(0)
            señal_real = señal_real.to(device)
            etiquetas = etiquetas.to(device)

            # ----------- ENTRENAMIENTO DEL DISCRIMINADOR -----------
            for x in range(critic_iter):
                noise = torch.randn((current_batch_size, dim_noise, 1), device=device)
                señal_fake_disc = generador(noise, etiquetas)

                valor_perdida_discriminador = funcion_perdida_discriminador(
                    discriminador, etiquetas, señal_real, señal_fake_disc, device, lambda_gp
                )

                optim_discriminador.zero_grad()
                valor_perdida_discriminador.backward(retain_graph=True)
                optim_discriminador.step()

            # ----------- ENTRENAMIENTO DEL GENERADOR -----------
            noise = torch.randn((current_batch_size, dim_noise, 1), device=device)
            señal_fake_gen = generador(noise, etiquetas)

            valor_perdida_generador = funcion_perdida_generador(discriminador, etiquetas, señal_fake_gen)

            optim_generador.zero_grad()
            valor_perdida_generador.backward()
            optim_generador.step()

            # Imprimir métricas de entrenamiento
            if verbose and j % 100 == 0:
                print(f"Época [{i+1}/{epochs}] - Batch [{j+1}/{len(dataloader)}] "
                      f"- Pérdida D: {valor_perdida_discriminador.item():.4f} "
                      f"- Pérdida G: {valor_perdida_generador.item():.4f}")

    print("El entrenamiento se ha completado.")

    # Guardar los modelos entrenados
    try:
        import datetime
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        gen_path = f"generador_final_{timestamp}.pth"
        disc_path = f"discriminador_final_{timestamp}.pth"

        torch.save(generador.state_dict(), gen_path)
        torch.save(discriminador.state_dict(), disc_path)

        print(f"Generador guardado en: {gen_path}")
        print(f"Discriminador guardado en: {disc_path}")

    except Exception as e:
        print(f"Error al guardar los modelos: {e}")

