# -*- coding: utf-8 -*-
"""FuncionesRepresentacionSenales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDK5SgUT0w0qZwKqWoWwsrGlPWuWXqrH

#**Funciones de representación de las señales por pantalla**

A continuación se definen las funciones que van a permitir la representación de las señales en pantalla, para poder llevar a cabo una evaluación visual de las mismas
"""



# Importación de las bibliotecas necesarias para el correcto funcionamiento de las señales

import numpy as np
import matplotlib.pyplot as plt



"""# Función que representa por pantalla una señal de ECG unidimensional"""

def representacion_señal_ecg (señal_ecg):
  """
  Esta función lleva a cabo la representción en pantalla de una señal de electrocardiograma (ECG), a la vez que muestra el número de muestras por las que esta se encuentra
  compuesta.

  Parámetros
  --------------
    - señal_ecg (np.array): Array que contiene los valores de la señal de ECG unidimensional que se va a mostrar por pantalla.

  Return
  --------------
    - None: La función no devuelve ningún valor, sino que realiza únicamente la representación.

  """
  plt.plot (señal_ecg)                                                   # Gráfica la señal de ECG unidimensional
  plt.show()                                                             # Muestra la figura creada por pantlla
  long_señal = len(señal_ecg)                                            # Calcula la longitud en número de muestras de la señal
  plt.title("Señal de electrocardiograma (ECG)")                         # Asigna un título a la gráfica de la señal
  plt.xlabel("Muestras de la señal")                                     # Asigna un título al eje OX
  plt.ylabel("Amplitud de la señal")                                     # Asigna un título al eje OY
  print (f"La señal incluye un total de {long_señal} muestras.")         # Muestra un mensaje por pantalla con el número de muestras que compone la señal



"""# Función que grafica la señal de ECG, señalando en rojo los picos R del complejo QRS"""

def representacion_picos_señales (señal_ecg, picos, fig_size = (12, 4)):
  """
  Esta función lleva a cabo la representación en pantalla de una señal de electrocardiograma (ECG), señalando en forma de cruces de color rojo los picos R que se han
  encontrado en la misma, para poder observar los valores por los que se puede llevar a cabo la segmentación de la señal.

  Parámetros
  --------------
    - señal_ecg (np.array): Array que contiene los valores de la señal de ECG unidimensional que se va a mostrar por pantalla.
    - picos (np.array): Array que contiene los índices de las posiciones en las que se han detectado los picos en la señal ECG.
    - fig_size (optional, tuple): Tamaño de la figura en pulgadas (ancho, alto). Por defecto es (12, 4).

  Return
  --------------
    - None: La función no devuelve ningún valor, sino que realiza únicamente la representación.
  """

  plt.figure(figsize=fig_size)                              # Crea una figura con las dimensiones indicadas, en cuyo interior se va a representar la señal de ECG
  plt.plot(señal_ecg, label='ECG')                          # Gráfica la señal de ECG unidimensional en la figuta que ha sido creada
  plt.plot(picos, señal_ecg[picos], "rx", label='Picos detectados en la señal')     # Dibuja los picos sobre la señal en forma de "x" de color rojo
  plt.title("Picos R de la señal de ECG")                   # Asigna un título al gráfico de la señal
  plt.xlabel("Muestras de la señal")                        # Asigna un título al eje OX
  plt.ylabel("Amplitud de la señal")                        # Asigna un título al eje OY
  plt.legend()                                              # Muestra la leyenda del gráfico
  plt.grid(True)                                            # Muestra la cuadrícula del gráfico
  plt.show()                                                # Muestra la figura creada por pantalla